#ifndef FCI_DEFENSE_PROFILE_H
#define FCI_DEFENSE_PROFILE_H

// Defense profile compile-time flags for FUSARIUM deployments
// Enable with -DFCI_DEFENSE_PROFILE

#ifdef FCI_DEFENSE_PROFILE
#define FCI_ENABLE_AES_GCM 1
#define FCI_ENABLE_CLASSIFICATION_TAGS 1
#define FCI_ENABLE_TAMPER_LOG 1
#define FCI_DEFAULT_CLASSIFICATION "CUI"
#else
#define FCI_ENABLE_AES_GCM 0
#define FCI_ENABLE_CLASSIFICATION_TAGS 0
#define FCI_ENABLE_TAMPER_LOG 0
#define FCI_DEFAULT_CLASSIFICATION "UNCLASSIFIED"
#endif

#endif // FCI_DEFENSE_PROFILE_H
